name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  NODE_VERSION: 16.18.1
  working-directory-webui: ./web-ui
  working-directory-vsc: ./vscode-extension

jobs:
  build:
    name: Build
    if: github.repository == 'fluxxus-nl/ATDD.TestScriptor.VSCodeExtension'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js v${{env.NODE_VERSION}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Use aurelia-cli
        run: npm install -g aurelia-cli
        working-directory: ${{env.working-directory-webui}}

      - name: Install
        run: npm install
        working-directory: ${{env.working-directory-webui}}

      - name: Run Build
        run: npm run build
        working-directory: ${{env.working-directory-webui}}

      - name: Use VSCE
        run: npm install -g vsce
        working-directory: ${{env.working-directory-vsc}}

      - name: Install
        run: npm install
        working-directory: ${{env.working-directory-vsc}}

      - name: Update package.json
        shell: pwsh
        run: '((Get-Content -path ./package.json -Raw) -replace ''"debugMode": true'',''"debugMode": false'') | Set-Content -Path ./package.json'
        working-directory: ${{env.working-directory-vsc}}

      - name: Run Build
        run: npx vsce package
        working-directory: ${{env.working-directory-vsc}}